/***************************************************************
 * Name:      MundialMain.h
 * Purpose:   Defines Application Frame
 * Author:    Karol Kowal, Marcin Kamiński, Paweł Niedziela (s98757@pollub.edu.pl, s98755@pollub.edu.pl, s98782@pollub.edu.pl)
 * Created:   2023-01-11
 * Copyright: Karol Kowal, Marcin Kamiński, Paweł Niedziela ()
 * License:
 **************************************************************/

#ifndef MUNDIALMAIN_H
#define MUNDIALMAIN_H
#include "Grupa.h"
#include "Druzyna.h"
#include "MeczeA.h"
#include "FazaPucharowa.h"
//(*Headers(MundialDialog)
#include <wx/button.h>
#include <wx/dialog.h>
#include <wx/sizer.h>
#include <wx/stattext.h>
//*)

class MundialDialog: public wxDialog
{
    friend class MeczeA;
    friend class FazaPucharowa;
    public:

        MundialDialog(wxWindow* parent,wxWindowID id = -1);
        virtual ~MundialDialog();

    private:

        //(*Handlers(MundialDialog)
        void OnQuit(wxCommandEvent& event);
        void OnAbout(wxCommandEvent& event);
        void OnGrajClick(wxCommandEvent& event);
        void OnInit(wxInitDialogEvent& event);
        void OnFPClick(wxCommandEvent& event);
        //*)

        //(*Identifiers(MundialDialog)
        static const long ID_STATICTEXT26;
        static const long ID_STATICTEXT1;
        static const long ID_STATICTEXT2;
        static const long ID_STATICTEXT3;
        static const long ID_STATICTEXT4;
        static const long ID_STATICTEXT5;
        static const long ID_STATICTEXT6;
        static const long ID_STATICTEXT7;
        static const long ID_STATICTEXT8;
        static const long ID_STATICTEXT9;
        static const long ID_STATICTEXT10;
        static const long ID_STATICTEXT11;
        static const long ID_STATICTEXT12;
        static const long ID_STATICTEXT13;
        static const long ID_STATICTEXT14;
        static const long ID_STATICTEXT15;
        static const long ID_STATICTEXT16;
        static const long ID_STATICTEXT17;
        static const long ID_STATICTEXT18;
        static const long ID_STATICTEXT19;
        static const long ID_STATICTEXT20;
        static const long ID_STATICTEXT21;
        static const long ID_STATICTEXT22;
        static const long ID_STATICTEXT23;
        static const long ID_STATICTEXT24;
        static const long ID_STATICTEXT25;
        static const long ID_STATICTEXT27;
        static const long ID_STATICTEXT28;
        static const long ID_STATICTEXT33;
        static const long ID_STATICTEXT38;
        static const long ID_STATICTEXT43;
        static const long ID_STATICTEXT48;
        static const long ID_STATICTEXT29;
        static const long ID_STATICTEXT34;
        static const long ID_STATICTEXT39;
        static const long ID_STATICTEXT44;
        static const long ID_STATICTEXT49;
        static const long ID_STATICTEXT30;
        static const long ID_STATICTEXT35;
        static const long ID_STATICTEXT40;
        static const long ID_STATICTEXT45;
        static const long ID_STATICTEXT50;
        static const long ID_STATICTEXT31;
        static const long ID_STATICTEXT36;
        static const long ID_STATICTEXT41;
        static const long ID_STATICTEXT46;
        static const long ID_STATICTEXT51;
        static const long ID_STATICTEXT32;
        static const long ID_STATICTEXT37;
        static const long ID_STATICTEXT42;
        static const long ID_STATICTEXT47;
        static const long ID_STATICTEXT52;
        static const long ID_STATICTEXT53;
        static const long ID_STATICTEXT54;
        static const long ID_STATICTEXT55;
        static const long ID_STATICTEXT56;
        static const long ID_STATICTEXT57;
        static const long ID_STATICTEXT58;
        static const long ID_STATICTEXT59;
        static const long ID_STATICTEXT60;
        static const long ID_STATICTEXT61;
        static const long ID_STATICTEXT62;
        static const long ID_STATICTEXT63;
        static const long ID_STATICTEXT64;
        static const long ID_STATICTEXT65;
        static const long ID_STATICTEXT66;
        static const long ID_STATICTEXT67;
        static const long ID_STATICTEXT68;
        static const long ID_STATICTEXT69;
        static const long ID_STATICTEXT70;
        static const long ID_STATICTEXT71;
        static const long ID_STATICTEXT72;
        static const long ID_STATICTEXT73;
        static const long ID_STATICTEXT74;
        static const long ID_STATICTEXT75;
        static const long ID_STATICTEXT76;
        static const long ID_STATICTEXT77;
        static const long ID_STATICTEXT78;
        static const long ID_STATICTEXT79;
        static const long ID_STATICTEXT85;
        static const long ID_STATICTEXT86;
        static const long ID_STATICTEXT87;
        static const long ID_STATICTEXT88;
        static const long ID_STATICTEXT89;
        static const long ID_STATICTEXT94;
        static const long ID_STATICTEXT93;
        static const long ID_STATICTEXT92;
        static const long ID_STATICTEXT91;
        static const long ID_STATICTEXT90;
        static const long ID_STATICTEXT99;
        static const long ID_STATICTEXT98;
        static const long ID_STATICTEXT97;
        static const long ID_STATICTEXT96;
        static const long ID_STATICTEXT95;
        static const long ID_STATICTEXT100;
        static const long ID_STATICTEXT101;
        static const long ID_STATICTEXT102;
        static const long ID_STATICTEXT103;
        static const long ID_STATICTEXT104;
        static const long ID_STATICTEXT105;
        static const long ID_STATICTEXT106;
        static const long ID_STATICTEXT107;
        static const long ID_STATICTEXT108;
        static const long ID_STATICTEXT109;
        static const long ID_STATICTEXT80;
        static const long ID_STATICTEXT81;
        static const long ID_STATICTEXT127;
        static const long ID_STATICTEXT128;
        static const long ID_STATICTEXT129;
        static const long ID_STATICTEXT130;
        static const long ID_STATICTEXT82;
        static const long ID_STATICTEXT123;
        static const long ID_STATICTEXT124;
        static const long ID_STATICTEXT125;
        static const long ID_STATICTEXT126;
        static const long ID_STATICTEXT83;
        static const long ID_STATICTEXT119;
        static const long ID_STATICTEXT120;
        static const long ID_STATICTEXT121;
        static const long ID_STATICTEXT122;
        static const long ID_STATICTEXT84;
        static const long ID_STATICTEXT115;
        static const long ID_STATICTEXT116;
        static const long ID_STATICTEXT117;
        static const long ID_STATICTEXT118;
        static const long ID_STATICTEXT110;
        static const long ID_STATICTEXT111;
        static const long ID_STATICTEXT112;
        static const long ID_STATICTEXT113;
        static const long ID_STATICTEXT114;
        static const long ID_STATICTEXT131;
        static const long ID_STATICTEXT132;
        static const long ID_STATICTEXT133;
        static const long ID_STATICTEXT134;
        static const long ID_STATICTEXT135;
        static const long ID_STATICTEXT136;
        static const long ID_STATICTEXT137;
        static const long ID_STATICTEXT138;
        static const long ID_STATICTEXT139;
        static const long ID_STATICTEXT140;
        static const long ID_STATICTEXT141;
        static const long ID_STATICTEXT146;
        static const long ID_STATICTEXT145;
        static const long ID_STATICTEXT144;
        static const long ID_STATICTEXT143;
        static const long ID_STATICTEXT142;
        static const long ID_STATICTEXT151;
        static const long ID_STATICTEXT150;
        static const long ID_STATICTEXT149;
        static const long ID_STATICTEXT148;
        static const long ID_STATICTEXT147;
        static const long ID_STATICTEXT152;
        static const long ID_STATICTEXT153;
        static const long ID_STATICTEXT154;
        static const long ID_STATICTEXT155;
        static const long ID_STATICTEXT156;
        static const long ID_STATICTEXT158;
        static const long ID_STATICTEXT184;
        static const long ID_STATICTEXT205;
        static const long ID_STATICTEXT206;
        static const long ID_STATICTEXT207;
        static const long ID_STATICTEXT208;
        static const long ID_STATICTEXT185;
        static const long ID_STATICTEXT201;
        static const long ID_STATICTEXT202;
        static const long ID_STATICTEXT203;
        static const long ID_STATICTEXT204;
        static const long ID_STATICTEXT186;
        static const long ID_STATICTEXT197;
        static const long ID_STATICTEXT198;
        static const long ID_STATICTEXT199;
        static const long ID_STATICTEXT200;
        static const long ID_STATICTEXT187;
        static const long ID_STATICTEXT193;
        static const long ID_STATICTEXT194;
        static const long ID_STATICTEXT195;
        static const long ID_STATICTEXT196;
        static const long ID_STATICTEXT188;
        static const long ID_STATICTEXT189;
        static const long ID_STATICTEXT190;
        static const long ID_STATICTEXT191;
        static const long ID_STATICTEXT192;
        static const long ID_STATICTEXT157;
        static const long ID_STATICTEXT159;
        static const long ID_STATICTEXT164;
        static const long ID_STATICTEXT169;
        static const long ID_STATICTEXT182;
        static const long ID_STATICTEXT183;
        static const long ID_STATICTEXT160;
        static const long ID_STATICTEXT165;
        static const long ID_STATICTEXT170;
        static const long ID_STATICTEXT180;
        static const long ID_STATICTEXT181;
        static const long ID_STATICTEXT161;
        static const long ID_STATICTEXT166;
        static const long ID_STATICTEXT171;
        static const long ID_STATICTEXT178;
        static const long ID_STATICTEXT179;
        static const long ID_STATICTEXT162;
        static const long ID_STATICTEXT167;
        static const long ID_STATICTEXT172;
        static const long ID_STATICTEXT176;
        static const long ID_STATICTEXT177;
        static const long ID_STATICTEXT163;
        static const long ID_STATICTEXT168;
        static const long ID_STATICTEXT174;
        static const long ID_STATICTEXT173;
        static const long ID_STATICTEXT175;
        static const long ID_BUTTON1;
        static const long ID_BUTTON2;
        //*)

        //(*Declarations(MundialDialog)
        wxButton* Button1;
        wxButton* FP;
        wxStaticText* BilansA1;
        wxStaticText* BilansA2;
        wxStaticText* BilansA3;
        wxStaticText* BilansA4;
        wxStaticText* BilansB1;
        wxStaticText* BilansB2;
        wxStaticText* BilansB3;
        wxStaticText* BilansB4;
        wxStaticText* BilansC1;
        wxStaticText* BilansC2;
        wxStaticText* BilansC3;
        wxStaticText* BilansC4;
        wxStaticText* BilansD1;
        wxStaticText* BilansD2;
        wxStaticText* BilansD3;
        wxStaticText* BilansD4;
        wxStaticText* BilansE1;
        wxStaticText* BilansE2;
        wxStaticText* BilansE3;
        wxStaticText* BilansE4;
        wxStaticText* BilansF1;
        wxStaticText* BilansF2;
        wxStaticText* BilansF3;
        wxStaticText* BilansF4;
        wxStaticText* BilansG1;
        wxStaticText* BilansG2;
        wxStaticText* BilansG3;
        wxStaticText* BilansG4;
        wxStaticText* BilansH1;
        wxStaticText* BilansH2;
        wxStaticText* BilansH3;
        wxStaticText* BilansH4;
        wxStaticText* NazwaA1;
        wxStaticText* NazwaA2;
        wxStaticText* NazwaA3;
        wxStaticText* NazwaA4;
        wxStaticText* NazwaB1;
        wxStaticText* NazwaB2;
        wxStaticText* NazwaB3;
        wxStaticText* NazwaB4;
        wxStaticText* NazwaC1;
        wxStaticText* NazwaC2;
        wxStaticText* NazwaC3;
        wxStaticText* NazwaC4;
        wxStaticText* NazwaD1;
        wxStaticText* NazwaD2;
        wxStaticText* NazwaD3;
        wxStaticText* NazwaD4;
        wxStaticText* NazwaE1;
        wxStaticText* NazwaE2;
        wxStaticText* NazwaE3;
        wxStaticText* NazwaE4;
        wxStaticText* NazwaF1;
        wxStaticText* NazwaF2;
        wxStaticText* NazwaF3;
        wxStaticText* NazwaF4;
        wxStaticText* NazwaG1;
        wxStaticText* NazwaG2;
        wxStaticText* NazwaG3;
        wxStaticText* NazwaG4;
        wxStaticText* NazwaH1;
        wxStaticText* NazwaH2;
        wxStaticText* NazwaH3;
        wxStaticText* NazwaH4;
        wxStaticText* PunktyA1;
        wxStaticText* PunktyA2;
        wxStaticText* PunktyA3;
        wxStaticText* PunktyA4;
        wxStaticText* PunktyB1;
        wxStaticText* PunktyB2;
        wxStaticText* PunktyB3;
        wxStaticText* PunktyB4;
        wxStaticText* PunktyC1;
        wxStaticText* PunktyC2;
        wxStaticText* PunktyC3;
        wxStaticText* PunktyC4;
        wxStaticText* PunktyD1;
        wxStaticText* PunktyD2;
        wxStaticText* PunktyD3;
        wxStaticText* PunktyD4;
        wxStaticText* PunktyE1;
        wxStaticText* PunktyE2;
        wxStaticText* PunktyE3;
        wxStaticText* PunktyE4;
        wxStaticText* PunktyF1;
        wxStaticText* PunktyF2;
        wxStaticText* PunktyF3;
        wxStaticText* PunktyF4;
        wxStaticText* PunktyG1;
        wxStaticText* PunktyG2;
        wxStaticText* PunktyG3;
        wxStaticText* PunktyG4;
        wxStaticText* PunktyH1;
        wxStaticText* PunktyH2;
        wxStaticText* PunktyH3;
        wxStaticText* PunktyH4;
        wxStaticText* StaticText10;
        wxStaticText* StaticText11;
        wxStaticText* StaticText12;
        wxStaticText* StaticText13;
        wxStaticText* StaticText14;
        wxStaticText* StaticText15;
        wxStaticText* StaticText16;
        wxStaticText* StaticText17;
        wxStaticText* StaticText18;
        wxStaticText* StaticText19;
        wxStaticText* StaticText1;
        wxStaticText* StaticText20;
        wxStaticText* StaticText21;
        wxStaticText* StaticText22;
        wxStaticText* StaticText23;
        wxStaticText* StaticText24;
        wxStaticText* StaticText25;
        wxStaticText* StaticText26;
        wxStaticText* StaticText2;
        wxStaticText* StaticText31;
        wxStaticText* StaticText32;
        wxStaticText* StaticText33;
        wxStaticText* StaticText36;
        wxStaticText* StaticText39;
        wxStaticText* StaticText3;
        wxStaticText* StaticText40;
        wxStaticText* StaticText45;
        wxStaticText* StaticText46;
        wxStaticText* StaticText4;
        wxStaticText* StaticText51;
        wxStaticText* StaticText52;
        wxStaticText* StaticText57;
        wxStaticText* StaticText58;
        wxStaticText* StaticText59;
        wxStaticText* StaticText5;
        wxStaticText* StaticText60;
        wxStaticText* StaticText61;
        wxStaticText* StaticText62;
        wxStaticText* StaticText63;
        wxStaticText* StaticText6;
        wxStaticText* StaticText7;
        wxStaticText* StaticText84;
        wxStaticText* StaticText85;
        wxStaticText* StaticText86;
        wxStaticText* StaticText87;
        wxStaticText* StaticText88;
        wxStaticText* StaticText8;
        wxStaticText* StaticText9;
        wxStaticText* StraconeA1;
        wxStaticText* StraconeA2;
        wxStaticText* StraconeA3;
        wxStaticText* StraconeA4;
        wxStaticText* StraconeB1;
        wxStaticText* StraconeB2;
        wxStaticText* StraconeB3;
        wxStaticText* StraconeB4;
        wxStaticText* StraconeC1;
        wxStaticText* StraconeC2;
        wxStaticText* StraconeC3;
        wxStaticText* StraconeC4;
        wxStaticText* StraconeD1;
        wxStaticText* StraconeD2;
        wxStaticText* StraconeD3;
        wxStaticText* StraconeD4;
        wxStaticText* StraconeE1;
        wxStaticText* StraconeE2;
        wxStaticText* StraconeE3;
        wxStaticText* StraconeE4;
        wxStaticText* StraconeF1;
        wxStaticText* StraconeF2;
        wxStaticText* StraconeF3;
        wxStaticText* StraconeF4;
        wxStaticText* StraconeG1;
        wxStaticText* StraconeG2;
        wxStaticText* StraconeG3;
        wxStaticText* StraconeG4;
        wxStaticText* StraconeH1;
        wxStaticText* StraconeH2;
        wxStaticText* StraconeH3;
        wxStaticText* StraconeH4;
        wxStaticText* ZdobyteA1;
        wxStaticText* ZdobyteA2;
        wxStaticText* ZdobyteA3;
        wxStaticText* ZdobyteA4;
        wxStaticText* ZdobyteB1;
        wxStaticText* ZdobyteB2;
        wxStaticText* ZdobyteB3;
        wxStaticText* ZdobyteB4;
        wxStaticText* ZdobyteC1;
        wxStaticText* ZdobyteC2;
        wxStaticText* ZdobyteC3;
        wxStaticText* ZdobyteC4;
        wxStaticText* ZdobyteD1;
        wxStaticText* ZdobyteD2;
        wxStaticText* ZdobyteD3;
        wxStaticText* ZdobyteD4;
        wxStaticText* ZdobyteE1;
        wxStaticText* ZdobyteE2;
        wxStaticText* ZdobyteE3;
        wxStaticText* ZdobyteE4;
        wxStaticText* ZdobyteF1;
        wxStaticText* ZdobyteF2;
        wxStaticText* ZdobyteF3;
        wxStaticText* ZdobyteF4;
        wxStaticText* ZdobyteG1;
        wxStaticText* ZdobyteG2;
        wxStaticText* ZdobyteG3;
        wxStaticText* ZdobyteG4;
        wxStaticText* ZdobyteH1;
        wxStaticText* ZdobyteH2;
        wxStaticText* ZdobyteH3;
        wxStaticText* ZdobyteH4;
        //*)


        DECLARE_EVENT_TABLE()
};

#endif // MUNDIALMAIN_H
